{
 "title": "At Risk Single Device",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "device", "label": "device", "query": "up{job='node'}" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 * (1 - avg by(instance)(irate(node_cpu_seconds_total{job='node',mode='idle',instance=$device}[5m])))"
    }
   ]
  },
  {
   "title": "Temp",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "topk(10,(node_hwmon_temp_celsius{chip=\"iwlwifi\",sensor=\"temp1\",instance=$device})*9/5+32)"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(node_memory_MemFree_bytes{job='node',instance=$device} + node_memory_Cached_bytes{job='node',instance=$device} + node_memory_Buffers_bytes{job='node',instance=$device})/1000000"
    }
   ]
  },
  {
   "title": "FileSystem Fullness",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 - node_filesystem_free_bytes{job='node',instance=$device,mountpoint='/'} / node_filesystem_size_bytes{job='node'} * 100"
    }
   ]
  },
  {
   "title": "Last Connected Wifi SSID",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "node_wifi_station_info{job='node',instance=$device}"
    }
   ]
  },
  {
   "title": "Wifi Signal Strength",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "2 * (node_wifi_station_signal_dbm{job='node',instance=$device} + 100)",
     "legendFormat": "Quality (%)"
    },
    {
     "expr": "node_wifi_station_signal_dbm{job='node',instance=$device}",
     "legendFormat": "RSSI (dBm)"
    }
   ]
  },
  {
   "title": "Total Wifi Received",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{job='node',device='wlp1s0',instance=$device}"
    }
   ]
  },
  {
   "title": "Total Ethernet Received",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{job='node',device=~'enp0s20.*',instance=$device}"
    }
   ]
  },
  {
   "title": "Device Temp",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,(node_hwmon_temp_celsius{chip=\"iwlwifi\",sensor=\"temp1\",instance=$device})*9/5+32)"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "100 * (avg by (mode)(irate(node_cpu_seconds_total{job='node',instance=$device,mode!='idle'}[5m])))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job='node',instance=$device,device='balena0'}[5m])",
     "legendFormat": "balena0 Received"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job='node',instance=$device,device='balena0'}[5m])",
     "legendFormat": "balena0 Transmitted"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job='node',instance=$device,device='resin-vpn'}[5m])",
     "legendFormat": "resin-vpn Received"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job='node',instance=$device,device='resin-vpn'}[5m])",
     "legendFormat": "resin-vpn Transmitted"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job='node',instance=$device,device='wlp1s0'}[5m])",
     "legendFormat": "wlp1s0 Transmitted"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job='node',instance=$device,device='wlp1s0'}[5m])",
     "legendFormat": "wlp1s0 Received"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job='node',instance=$device,device=~'enp0s20.*'}[5m])",
     "legendFormat": "enp0s20 Received"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job='node',instance=$device,device=~'enp0s20.*'}[5m])",
     "legendFormat": "enp0s20 Trasmitted"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job='node',instance=$device}  / 1000000",
     "legendFormat": " memory_MemFree"
    },
    {
     "expr": "node_memory_Cached_bytes{job='node',instance=$device}  / 1000000",
     "legendFormat": "memory_Cached"
    },
    {
     "expr": " node_memory_Buffers_bytes{job='node',instance=$device}  / 1000000",
     "legendFormat": "memory_Buffers"
    }
   ]
  },
  {
   "title": "FileSystem Fullness",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "100 - node_filesystem_free_bytes{job='node',instance=$device,mountpoint='/'} / node_filesystem_size_bytes{job='node'} * 100",
     "legendFormat": " "
    },
    {},
    {}
   ]
  }
 ]
}