{
 "title": "At Risk Devices",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Hottest Devices (°F)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,(node_hwmon_temp_celsius{chip=\"iwlwifi\",sensor=\"temp1\"})*9/5+32)"
    }
   ]
  },
  {
   "title": "Hottest",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max((node_hwmon_temp_celsius{chip=\"iwlwifi\",sensor=\"temp1\"}*9/5+32))"
    }
   ]
  },
  {
   "title": "Coldest",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min((node_hwmon_temp_celsius{chip=\"iwlwifi\",sensor=\"temp1\"}*9/5+32))"
    }
   ]
  },
  {
   "title": "Total Devices at Risk",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg"
  },
  {
   "title": "Hottest Devices (°F)",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "topk(10,(node_hwmon_temp_celsius{chip=\"iwlwifi\",sensor=\"temp1\"})*9/5+32)",
     "legendFormat": "{{resin_device_name}}"
    }
   ]
  },
  {
   "title": "Least Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bottomk(10, node_memory_MemFree_bytes{job='node'} + node_memory_Cached_bytes{job='node'} + node_memory_Buffers_bytes{job='node'})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Highest CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "topk(2, 100 * (1 - avg by(instance)(irate(node_cpu_seconds_total{job='node',mode='idle'}[5m]))))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Current Least Memory (GB) (Bottom 10)",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sort_desc(bottomk(10, (node_memory_MemFree_bytes{job='node'} + node_memory_Cached_bytes{job='node'} + node_memory_Buffers_bytes{job='node'}) / 1000000000))"
    }
   ]
  },
  {
   "title": "Fullest Disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "topk(5, 100 - node_filesystem_free_bytes{job='node',mountpoint='/'} / node_filesystem_size_bytes{job='node'} * 100)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Current Highest CPU Usage (Top 10)",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "sort(topk(10, 100 * (1 - avg by(resin_device_name,resin_device_uuid)(irate(node_cpu_seconds_total{job='node',mode='idle'}[5m])))))"
    }
   ]
  },
  {
   "title": "Avg Network Usage Per Device Per Hour (MB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_network_receive_bytes_total{job='node',device!='lo'}[1h])) * 60 * 60 / 1000000",
     "legendFormat": "Avg Network Received / Hour (MB)"
    },
    {
     "expr": "avg(rate(node_network_transmit_bytes_total{job='node',device!='lo'}[1h])) * 60 * 60 / 1000000",
     "legendFormat": "Avg Network Transmit / Hour (MB)"
    }
   ]
  },
  {
   "title": "Current Highest Disk Usage (Top 10)",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "sort(topk(10, 100 - node_filesystem_free_bytes{job='node',mountpoint='/'} / node_filesystem_size_bytes{job='node'} * 100))"
    }
   ]
  },
  {
   "title": "Highest Total Network Receive (GB)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "sort(topk(10, (sum by (resin_device_name,resin_device_uuid)(node_network_receive_bytes_total{job='node',device!='lo'})) / 1000000000))"
    }
   ]
  }
 ]
}